hashgraph/hedera-transaction-tool

front-end/src/renderer/components/AccountIdInput.vue, front-end/src/renderer/components/Transaction/Create/AccountData/AccountDataFormData.vue, front-end/src/renderer/components/Transaction/Create/AccountDelete/AccountDeleteFormData.vue, front-end/src/renderer/components/Transaction/Create/AccountUpdate/AccountUpdateFormData.vue, front-end/src/renderer/components/Transaction/TransactionIdControls.vue, front-end/src/renderer/components/TransferCard.vue, front-end/src/renderer/components/ui/AppAutoComplete.vue, front-end/src/renderer/components/ui/AppInput.vue, front-end/src/renderer/stores/storeUser.ts, front-end/src/renderer/styles/_ui-elements.scss, front-end/src/renderer/utils/sdk/index.ts
This pull request updates the behavior of the regular AppAutoComplete and adds a specific AccountIdInput, which wraps the regular AppAutoComplete and provides better UX with updated input formatting
Fixes #
#855
=> feat: update AppAutoComplete behaviour

front-end/src/renderer/components/Transaction/TransactionGroupProcessor.vue, front-end/src/renderer/components/ui/AppModal.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/stores/storeTransactionGroup.ts
fixes:
- Spacing on individual transaction buttons is incorrect
- Transfer Transaction title is incorrect on import
- duplicated transactions don't show second column
- Header/Footer should be sticky on confirm group modal
- Create Transaction Group Title area should be sticky
Fixes #1193
**Checklist**
=> fix: miscellaneous fixes for styling in transaction group

back-end/apps/api/src/user-keys/user-keys.controller.spec.ts, back-end/apps/api/src/user-keys/user-keys.controller.ts, back-end/apps/api/src/user-keys/user-keys.service.spec.ts, back-end/apps/api/src/user-keys/user-keys.service.ts, back-end/apps/api/test/spec/user-keys.e2e-spec.ts, front-end/src/renderer/stores/storeTransactionGroup.ts
This pull request removes the mnemonicHash and the index of the key object when making a request for another user's keys
Fixes #
#1123 
**Checklist**
=> feat: remove mnemonic information of another user from response

back-end/apps/api/src/transactions/transactions.service.ts, back-end/apps/api/test/spec/transaction.e2e-spec.ts, back-end/libs/common/src/database/entities/transaction.entity.ts
This pull request enables the submission of transactions with an ID that has already been sent but is canceled or rejected
Fixes #
#1079 
**Checklist**
=> feat: allow submission of canceled transaction

back-end/k8s/dev/deployments/api-deployment.yaml, back-end/k8s/dev/deployments/chain-deployment.yaml, back-end/k8s/dev/deployments/notifications-deployment.yaml
This pull request adds the new POSTGRES_MAX_POOL_SIZE env variable inside the deployment files for the local Kubernetes deployment
=> fix: missing env variable from develop deployment

front-end/src/main/services/localUser/dataMigration.ts, front-end/src/tests/main/services/localUser/dataMigration.spec.ts
This pull request adds '/InputFiles' to the updates location when migrating the user from the old tool
=> feat: add /InputFiles suffix when migrating

.github/workflows/test-backend.yaml
pnpm/action-setup has to be replaced with a variant maintained by step-security in all workflows utilizing the action.
Fixes #1262 
N/A
**Checklist**
=> chore: replace pnpm/action-setup with a step-security maintained one

front-end/src/renderer/components/ui/AppDropDown.vue
AppDropDown wasn't using the text-body class. This caused the text color to be incorrect in light mode.
Fixes #1321 
Thanks for showing me how to do this, Svet!
=> fix: updated color of the dropdown to be the same as other components

NOTICE, back-end/apps/api/src/auth/auth.controller.spec.ts, back-end/apps/api/src/auth/auth.service.spec.ts, back-end/apps/api/src/auth/auth.service.ts, back-end/apps/api/test/spec/auth.e2e-spec.ts, front-end/src/renderer/components/Contacts/ContactDetails.vue
Backend Changes:
- Integrated the resend email with temporary password feature (only admin)  to newly registered users.
- Unit Tests:
Added unit tests to validate the logic for resending emails and updating user details.
- e2e Tests:
Implemented e2e tests to ensure the feature works as expected through API endpoints.
Frontend Changes:
- Updated the frontend interface to support the resend email feature.
- Added UI element for triggering the resend email action (only to users with status === 'NEW').
- Included error and success handling (toast messages).
#1147
=> 1147 add feature to resend new user emails

front-end/src/renderer/components/ui/AppPasswordInput.vue, front-end/src/renderer/pages/UserLogin/components/EmailLoginForm.vue
Force inherited the is-invalid class to the div wrapper in AppPasswordInput.
Bootstrap's is-invalid and invalid-feedback don't behave as expected when the is-invalid component is a compound component that does not bind the attrs to the root component. In this case, the invalid-feedback component looks for the nearest component that has is-invalid and binds to it.
Fixes #1378 
**Checklist**
=> fix: force inherited the is-invalid class

automation/pages/AccountPage.js, automation/pages/FilePage.js, automation/tests/workflowTests.test.js, front-end/src/main/windows/mainWindow.ts, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/EncryptedKeysBox.vue, front-end/src/renderer/pages/Accounts/Accounts.vue, front-end/src/renderer/pages/Files/Files.vue, front-end/src/renderer/pages/Migrate/Migrate.vue
- Remove Button Visibility:
The "Remove" (for a single item) buttons in Accounts and Files pages are now only visible when the "Select" button is not active.
If the "Select" button is active, the "Remove" button is relocated underneath the "Select" button.
- Files Page:
Code improvement and matching logic with that in Accounts page.
#1379
=> feat: improve accounts & files pages

front-end/src/renderer/components/ui/AppDropDown.vue
Simple text color fix (class names) in AppDropDown component
Fixes #
#1392
=> fix: active dropdown colors in light mode

front-end/src/renderer/components/Header.vue
Fix: Network label in header used as a link to 'settings/general'
#1434
=> fix: header link

front-end/src/renderer/components/Approvers/ApproverModal.vue, front-end/src/renderer/components/ComplexKey/ComplexKeyModal.vue, front-end/src/renderer/components/ComplexKey/ComplexKeySaveKeyModal.vue, front-end/src/renderer/components/ComplexKey/ComplexKeySelectAccountModal.vue, front-end/src/renderer/components/ComplexKey/ComplexKeySelectSavedKey.vue, front-end/src/renderer/components/DataMigration/DecryptMnemonicPhrase.vue, front-end/src/renderer/components/ForgotPasswordModal.vue, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/DecryptKeyModal.vue, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/SelectEncryptedKeysModal.vue, front-end/src/renderer/components/Organization/AddOrSelectModal.vue, front-end/src/renderer/components/Organization/AddOrganizationModal.vue, front-end/src/renderer/components/Organization/OrganizationStatusModal.vue, front-end/src/renderer/components/Organization/SelectOrganizationModal.vue, front-end/src/renderer/components/Organization/UserSelectModal.vue, front-end/src/renderer/components/UserPasswordModal.vue, front-end/src/renderer/components/modals/UpdateNicknameModal.vue, front-end/src/renderer/components/ui/ButtonGroup.vue, front-end/src/renderer/pages/AccountSetup/components/NewPassword.vue, front-end/src/renderer/pages/Accounts/LinkExistingAccount/LinkExistingAccount.vue, front-end/src/renderer/pages/ContactList/SignUpUser/SignUpUser.vue, front-end/src/renderer/pages/Files/LinkExistingFile/LinkExistingFile.vue, front-end/src/renderer/pages/Migrate/components/DecryptRecoveryPhraseForm.vue, front-end/src/renderer/pages/Migrate/components/SetupPersonal.vue, front-end/src/renderer/pages/RestoreKey/RestoreKey.vue, front-end/src/renderer/pages/RestoreKey/components/ImportStep.vue, front-end/src/renderer/pages/RestoreKey/components/RestoreStep.vue, front-end/src/renderer/pages/RestoreKey/components/SaveStep.vue, front-end/src/renderer/pages/Settings/components/GeneralTab/components/AppearanceSettings.vue, front-end/src/renderer/pages/Settings/components/GeneralTab/components/NetworkSettings.vue, front-end/src/renderer/pages/Settings/components/WorkGroupsTab.vue
- Refactor of RestoreKey page, each step of it is represented by an individual, self-contained component.
- Replaced all @submit instances in the codebase with @submit.prevent. Removed e.preventDefault() in the handlers.
- Created ButtonGroup reusable component
#1442
=> refactor: RestoreKey, feat: ButtonGroup

front-end/src/renderer/components/Menu.vue
The page/tab buttons in the menu on the left hand side have now been set to not-draggable.
Fixes #1446
=> fix: remove drag tooltip on menu page buttons

automation/tests/transactionTests.test.js, front-end/src/renderer/components/AccountIdsSelect.vue, front-end/src/renderer/pages/Settings/components/KeysTab/KeysTab.vue
Color fix of account id in settings -> keys. The account id and it's checksum is now with the color of the user's current network.
AccountIdsSelect (used for selecting account ids in personal mode) is now showing the checksum too.
=> fix: accountId color in KeysTab, fix: AccountIdsSelect

front-end/src/renderer/components/ui/AppAutoComplete.vue
Fix for dropdown in AppAutoComplete (now it loops and handles auto scrolling properly).
PS: Looping is not removed but rather fixed (bug in the code), can remove it if it is necessary.
This PR includes the changes requested in #1427 
#1467
=> fix: list loop and auto scroll in AppAutoComplete

NOTICE, front-end/package.json, front-end/pnpm-lock.yaml, front-end/src/renderer/pages/TransactionDetails/TransactionDetails.vue, front-end/src/renderer/pages/TransactionDetails/components/TransactionDetailsHeader.vue, front-end/src/renderer/stores/storeNextTransaction.ts
This pull request adds a previous button together with the next button
Fixes #835
=> feat: add previous button

front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransactionModal.vue
This PR adds the missing explanatory text and icon in modals, along with a missed conditional logic for route leave when the user is logging out. These were not included in the previous bug fix for tracking changes in drafts.
#1547
=> fix: explanatory text & icon in modal, fix: skip modal on logout

front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseGroupHandler.vue, front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransaction.vue, front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransactionModal.vue
This PR improves 'on route leave' logic, adds a new modal to warn users when leaving a 'create transaction' page during the process of group creating/editing, and includes a minor refactor of the components used in the flow.
none
Fixes #
BaseTransactionModal, BaseTransaction, BaseGroupHandler
=> feat: unsaved group modal, fix: route leave logic

front-end/src/renderer/components/ui/AppAutoComplete.vue
This PR includes two fixes for the AppAutoComplete reusable component: ensuring correct scrolling to the auto-suggested account in the dropdown while typing and modifying the handler function logic for the keydown event.
#1534 #1536
=> fix: scrolling to auto-suggested  in AppAutoComplete, fix: handler function

back-end/apps/chain/src/execute/execute.service.spec.ts, back-end/apps/chain/src/execute/execute.service.ts, front-end/src/renderer/pages/TransactionDetails/components/TransactionDetailsHeader.vue
Added a filter in the backend's execute service to exclude canceled transactions within a group. Since executeTransactionGroup validates all submitted transactions, this ensures that any transaction canceled in the meantime is properly filtered out.
#1376
=> feat: filter canceled transactions in a group

front-end/src/main/modules/ipcHandlers/localUser/keyPairs.ts, front-end/src/main/services/localUser/keyPairs.ts, front-end/src/preload/localUser/keyPairs.ts, front-end/src/renderer/components/ui/AppDatePicker.vue, front-end/src/renderer/composables/useMatchRecoveryPhrase.ts, front-end/src/renderer/pages/MatchRecoveryPhrase/MatchRecoveryPhrase.vue, front-end/src/renderer/pages/MatchRecoveryPhrase/index.ts, front-end/src/renderer/pages/RestoreKey/components/ImportStep.vue, front-end/src/renderer/pages/Settings/components/KeysTab/components/TabHeading.vue, front-end/src/renderer/router/constants.ts, front-end/src/renderer/router/index.ts, front-end/src/renderer/services/keyPairService.ts, front-end/src/renderer/styles/_layout.scss, front-end/src/tests/main/modules/ipcHandlers/localUser/keyPairs.spec.ts, front-end/src/tests/main/services/localUser/keyPairs.spec.ts
This pull request creates a page for matching recovery phrases to an external key
Fixes #1245
=> feat: add auto mnemonic matching

front-end/src/renderer/pages/Migrate/Migrate.vue, front-end/src/renderer/pages/Migrate/components/Summary.vue, front-end/src/renderer/pages/Migrate/components/SummaryItem.vue
Summary step of the migration flow now shows the recovery phrase in a more familiar way. Copying the phrase also is done in the 'standard' format used throughout the app.
Fixes #1284 
**Checklist**
=> 1284 copy pasting in all places of the recovery phrase should copy and paste the same format

front-end/src/renderer/components/ImportExternalPrivateKeyModal.vue, front-end/src/renderer/pages/RestoreMissingKeys/RestoreMissingKeys.vue, front-end/src/renderer/pages/Settings/components/KeysTab/KeysTab.vue, front-end/src/renderer/router/index.ts, front-end/src/renderer/services/keyPairService.ts, front-end/src/renderer/types/index.ts, front-end/src/renderer/utils/sdk/index.ts
Added button and modified flows to allow the user to recover keys after reconnecting to an organization. Previously, the user was directed to delete keys. Now they have both options
Fixes #866 
**Checklist**
=> 866 rename delete missing key to something that will let the user know to re upload their key

front-end/src/renderer/components/ui/AppStepper.vue, front-end/src/renderer/pages/TransactionDetails/TransactionDetails.vue, front-end/src/renderer/pages/TransactionDetails/components/TransactionDetailsHeader.vue, front-end/src/renderer/pages/TransactionDetails/components/TransactionDetailsStatusStepper.vue, front-end/src/renderer/pages/UserLogin/components/KeychainOption.vue, front-end/src/renderer/utils/transactions.ts
Added a failed message banner and fixed the Transaction Status stepper to show the proper color, icon, and message for each status.
Fixes #1562 
**Checklist**
=> feat: display failed code message banner and proper status step

.github/workflows/publish-docker-images.yaml
This PR introduces a new github workflow which builds the chain, API, and notifications containers on every tag of this repository. 
Additionally, it allows you to do a workflow dispatch to build the main branch.
=> feat: Add docker image builds

README.md
The current link https://docs.hedera.com/hedera-transactions-tool listed in the README is no longer working. This is the updated link https://docs.hedera.com/hedera-transaction-tool-v2
=> Update README.md for working link

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json, front-end/src/renderer/composables/user/useAfterOrganizationSelection.ts, front-end/src/renderer/pages/Migrate/Migrate.vue
A specific flow used during migration was causing the wrong steps to appear. This has been resolved by further assuring that the normal routing rules are bypassed or ignored during migration.
Fixes #1699
=> fix: 1699 during migration the option to create a new recovery phrase use existing or importing existing recovery phrase still displays

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json, front-end/src/main/shared/constants/index.ts, front-end/src/renderer/composables/useAutoLogin.ts, front-end/src/renderer/pages/Migrate/Migrate.vue, front-end/src/renderer/pages/Migrate/components/SetupOrganizationForm.vue, front-end/src/renderer/pages/Migrate/components/Summary.vue, front-end/src/renderer/pages/Settings/components/ProfileTab.vue, front-end/src/renderer/services/userService.ts
If the user chooses to create the personal account using an email/password during the migration process, the org setup process didn't allow the user to use a different email for the org.
=> fix: Migration reuse username if applicable

front-end/src/renderer/utils/sdk/index.ts
Change stringifyHbar() such that it always displays the hbar amount in decimal notation -- and not using scientific notation -- in case of small amounts of tiny bars.
Fixes #1764
Without fix:
With fix:
=> fix: 1764 display leading zeros in hbar amounts

front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransaction.vue, front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransactionModal.vue
When leaving draft editing, we compare the transaction data (excluding the validStart) with a snapshot taken before the edit to determine whether we need to show the discard/save modal.
When creating a draft from scratch, we set a 500ms timer after the view is mounted to make sure the transaction is fully initialized before we can snapshot it.
Fixes #1794
This obsoletes the draft PR #1806, which I am going to close.
=> fix: do not ask to save new unaltered transaction drafts

back-end/apps/api/src/transactions/dto/index.ts, back-end/apps/api/src/transactions/dto/signature-import-result.dto.ts, back-end/apps/api/src/transactions/signers/signers.controller.spec.ts, back-end/apps/api/src/transactions/signers/signers.controller.ts, back-end/apps/api/src/transactions/signers/signers.service.spec.ts, back-end/apps/api/src/transactions/signers/signers.service.ts, back-end/apps/api/src/transactions/transactions.controller.spec.ts, back-end/apps/api/src/transactions/transactions.controller.ts, back-end/apps/api/src/transactions/transactions.service.spec.ts, back-end/apps/api/src/transactions/transactions.service.ts, back-end/libs/common/src/dtos/index.ts, front-end/src/renderer/services/organization/transaction.ts, front-end/src/shared/interfaces/organization/transactions/index.ts
Signatures from the Java Transaction Tool (TTv1) need to be supported by the latest Transaction Tool. An endpoint for the backend has been added to allow for importing signatures, in the form of a SignatureMap. The front end has been updated with the necessary code to call this endpoint, only. 
Fixes #1825 
**Checklist**
=> feat: importing signatures from TTv1 for backend storage

back-end/apps/api/src/transactions/dto/signature-import-result.dto.ts, back-end/apps/api/src/transactions/dto/upload-signature.dto.ts, back-end/apps/api/src/transactions/signers/signers.controller.spec.ts, back-end/apps/api/src/transactions/signers/signers.service.spec.ts, back-end/apps/api/src/transactions/signers/signers.service.ts, back-end/apps/api/src/transactions/transactions.controller.spec.ts, back-end/apps/api/src/transactions/transactions.service.spec.ts, back-end/apps/api/src/transactions/transactions.service.ts, front-end/src/renderer/services/organization/transaction.ts, front-end/src/shared/interfaces/organization/transactions/index.ts
Confusion exists between the transactionId of a transaction, and the id of a transaction. This caused an issue when handing work off from one person to another. For just the signature uploading, this has been changed to use the property name of 'id' instead of 'transactionId'. Some comments have also been added to help explain the name change. 
**Checklist**
=> chore: rename transactionId to id for signature uploads

front-end/src/renderer/components/SaveDraftButton.vue
Changes below removed the following unused properties from `SaveDraftButton` view:
- `props.handleSaveDraft`
- `props.handleDraftAdded`
- `props.handleDraftUpdated`
**Checklist**
=> chore: removed unused props from SaveDraftButton view
