NOTICE, automation/package.json, notice-gen/index.js
This pull request extends the notice generator to include the dependencies from the automation project also
=> feat: add automation dependencies to notice

front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue
match placeholders in node form data
Fixes #1203 
**Checklist**
=> fix: match placeholders in node form data

back-end/package.json, front-end/package.json
=> New version added

back-end/apps/api/src/setup-app.ts, back-end/apps/notifications/src/fan-out/fan-out.service.ts, front-end/src/main/shared/interfaces/organization/transactions/index.ts, front-end/src/renderer/components/AccountIdInput.vue, front-end/src/renderer/components/Transaction/Create/FileData/FileContentFormData.vue, front-end/src/renderer/components/Transaction/TransactionProcessor/components/BigFileOrganizationRequestHandler.vue, front-end/src/renderer/components/ui/AppAutoComplete.vue, front-end/src/renderer/components/ui/AppUploadFile.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/pages/Settings/components/GeneralTab/components/NetworkSettings.vue, front-end/src/renderer/pages/TransactionGroupDetails/TransactionGroupDetails.vue, front-end/src/renderer/stores/storeContacts.ts, front-end/src/renderer/stores/storeTransactionGroup.ts, front-end/src/renderer/utils/sdk/createTransactions.ts
This pull request fixes the following issues:
- service endpoint for node transactions in the front-end
- missing user in contact list if his keys request fails
- the notification service has a potential bottleneck because the email sender is not separated in different microservice and a minor change was made to process both email and in-app notifications in parallel
- fixes the autocomplete
- the group transaction details type
It also adds a limit for the files that can be uploaded
=> feat: minor changes & enhancements

front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue
add transfer labels in groups
Fixes #1073 
**Checklist**
=> feat: add transfer labels in groups, fix count when at 1 in groups

front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue
Switch Node Form Data field sizes
Fixes #1156 
**Checklist**
=> fix: switch cert field sizes

NOTICE
This notice was generated after `pnpm install`. 
Maybe was not committed?
@SvetBorislavov, please check if this need to be merged
=> feat: generated notice

front-end/src/renderer/pages/Settings/components/GeneralTab/components/NetworkSettings.vue
**Description**: Fix broken selector
Fixes #1234
**Checklist**
=> chore: Fix network tab selector

front-end/src/renderer/components/ui/AppRecoveryPhraseWord.vue, front-end/src/renderer/pages/AccountSetup/components/Generate.vue, front-end/src/renderer/styles/_utilities.scss
add border, add instruction, dont hide next button
Fixes #1192 
**Checklist**
=> fix: add border, add instruction, dont hide next button

front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransaction.vue, front-end/src/renderer/components/Transaction/TransactionIdControls.vue
load correct payer id in drafts
Fixes #1138
**Checklist**
=> fix: save payer ids in drafts, attempt at making balance update on load

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json
=> bump: version bump for the microservices

front-end/package.json
This pull request updates the repo URL and the author information inside the `package.json`
Fixes #
#400 
#1224
=> feat: update repo URL and author

front-end/src/renderer/components/AccountIdInput.vue, front-end/src/renderer/components/Transaction/Create/AccountDelete/AccountDeleteFormData.vue, front-end/src/renderer/components/TransferCard.vue
This pull request adds the account ids from the Account List by default, instead of provided by props
Fixes #
#657
=> feat: add accounts from account list in AccountId by default

NOTICE, notice-gen/index.js
This pull request adds ordering of the dependencies in the NOTICE file
=> fix: sort dependecies after fetch

front-end/src/renderer/styles/_ui-elements.scss
This pull request fixes the CSS style of the fullscreen modal
=> fix: style of fullscreen modal

back-end/package.json, front-end/package.json
Updates package.json version for FE and BE
=> feat: version updated

front-end/src/renderer/pages/RestoreMissingKeys/RestoreMissingKeys.vue, front-end/src/renderer/pages/Settings/components/ImportDropDown.vue
This pull request removes the initial cache of the recovery phrase after Account Setup when you:
- Go to Import -> Recovery Phrase
- Go to Restore Missing Keys
=> feat: mnemonic caching update

.github/workflows/test-backend.yaml, .github/workflows/test-frontend.yaml
This PR aims to roll-back codecov upload action to an older more stable version. Once issues are resolved in latest version we can re-update.
Fixes #1279 
**Checklist**
=> ci: Roll-back of codecov version due to issues with latest one. #395

front-end/src/renderer/components/Transaction/Create/AccountDelete/AccountDeleteFormData.vue, front-end/src/renderer/components/Transaction/Create/ApproveHbarAllowance/ApproveHbarAllowanceFormData.vue, front-end/src/renderer/components/Transaction/Create/FileContents/FileContents.vue, front-end/src/renderer/components/Transaction/TransactionIdControls.vue, front-end/src/renderer/components/TransferCard.vue, front-end/src/renderer/pages/Accounts/LinkExistingAccount/LinkExistingAccount.vue
Replaced conditional rendering of the label with dynamic content updates.
**Related issue(s)**: 1210
=> fix: balance label

front-end/src/main/modules/ipcHandlers/utils.ts, front-end/src/preload/localUser/utils.ts, front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue, front-end/src/renderer/services/electronUtilsService.ts, front-end/src/renderer/utils/sdk/createTransactions.ts
update DAB transactions
Fixes #1268 
**Checklist**
=> feat: update DAB transactions

front-end/src/renderer/components/ui/AppCheckBox.vue, front-end/src/renderer/pages/Accounts/Accounts.vue
Untrack all accounts at once (select all button) , displaying checkboxes by default
**Related issue(s)**: 1247 & 1248
Fixes #
Active account logic
=> feat: Select all, fix: selectedAccountIds logic

front-end/src/renderer/components/Transaction/Create/AccountCreate/AccountCreate.vue
Added a timeout-based refetch, ensuring the newly created account ID is accessible after successful transaction (account create).
**Related issue(s)**: 1184
=> fix: account id update

back-end/apps/api/src/auth/auth.service.ts
Updated temporary password generation in order to simplify the passwords without sacrificing security.
Fixes #1250 
**Checklist**
=> feat: simplify temporary passwords without sacrificing security

back-end/apps/api/src/users/users.service.spec.ts, back-end/apps/api/src/users/users.service.ts, back-end/apps/api/test/spec/auth.e2e-spec.ts
This pull request fixes the inability to restore users and adds e2e test for that case
Fixes #
#1313 
**Checklist**
=> fix: restore deleted user

back-end/apps/api/src/user-keys/user-keys.controller.spec.ts, back-end/apps/api/src/user-keys/user-keys.service.spec.ts, back-end/apps/api/src/user-keys/user-keys.service.ts, back-end/apps/api/test/spec/user-keys.e2e-spec.ts, back-end/libs/common/src/constants/errorCodes.ts, back-end/libs/common/src/constants/index.ts, front-end/src/main/shared/constants/errorCodes.ts
This pull request increases the max keys per user in the organization
Fixes #
#1239
**Checklist**
=> feat: increase max key size for backend

front-end/src/main/modules/ipcHandlers/utils.ts, front-end/src/preload/localUser/utils.ts, front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeCreate.vue, front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue, front-end/src/renderer/components/Transaction/Create/NodeUpdate/NodeUpdate.vue, front-end/src/renderer/services/electronUtilsService.ts, front-end/src/renderer/utils/sdk/createTransactions.ts, front-end/src/renderer/utils/sdk/getData.ts, front-end/src/tests/main/modules/ipcHandlers/utils.spec.ts
This pull request fixes the service endpoints handling and draft loading in Node Create & Node Update transactions
Fixes #
#1300
#1301 
#1286
=> fix: node create & update incorrect draft loading and service points

front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransaction.vue, front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue, front-end/src/renderer/utils/sdk/validation.ts
limit node description to 100 characters
Fixes #1287 
**Checklist**
=> fix: limit node description to 100 characters

front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue
remove extra new lines if they exist in grpccert input
Fixes #1288
**Checklist**
=> fix: remove extra new lines if they exist in grpccert input

front-end/src/main/services/localUser/dataMigration.ts, front-end/src/tests/main/services/localUser/dataMigration.spec.ts
Legacy decryption now supported
Fixes #1317 
A test was added, but automated tests still need to be added.
**Checklist**
=> fix: added legacy encryption support

front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue
add internal/external labels for gossip endpoints
Fixes #1285 
**Checklist**
=> feat: add internal/external labels for gossip endpoints

automation/README.md, automation/pages/GroupPage.js, automation/pages/RegistrationPage.js, automation/tests/groupTransactionTests.test.js, automation/utils/databaseQueries.js, automation/utils/databaseUtil.js, front-end/docs/api.md, front-end/src/renderer/components/EmptyTransactions.vue, front-end/src/renderer/components/Transaction/TransactionGroupProcessor.vue, front-end/src/renderer/components/Transaction/TransactionHeaderControls.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/tests/main/windows/mainWindow.spec.ts
**Description**: This PR introduces new tests for group transaction in personal mode
Fixes #1218
**Notes for reviewer**: 
**Checklist**
=> test: Add tests for group tx in personal mode

back-end/apps/api/.env.test, back-end/apps/api/example.env, back-end/apps/api/src/main.ts, back-end/apps/chain/example.env, back-end/apps/notifications/example.env, back-end/example.env
Updated the .env variables with defaults. No longer need to update these configs as instructed in the readme for development. Many pain points observed when new contributors are trying to get their development set up working and missing places to update the .env file. Also to provide a default for NODE_ENV= which maps to the development env.
Fixes 
#1022 
#1348 
**Checklist**
=> feat: update dev env variables

NOTICE, automation/package.json, automation/pages/OrganizationPage.js, automation/pnpm-lock.yaml, automation/utils/crypto.js
**Description**: After latest hashing changes, automation tests needs to be adapted.
Fixes #
**Checklist**
=> test: fix automation hashing

front-end/src/renderer/pages/ContactList/ContactList.vue
Simple sort of contactList array (ContactList.vue page)
#1282
=> feat: sort contact list

front-end/src/renderer/main.ts
Set global duration option for toast messages (vue-toast-notification).
#1283
=> fix: global duration option for toast messages

front-end/electron-builder.yml
=> fix: electron-builder.yml

front-end/src/renderer/components/UserModeSelect.vue
**Description**: Update "Personal mode" to "Personal"
Fixes #1354 
**Checklist**
=> update personal mode

front-end/README.md
This pull request updates the front-end README file with the latest requirements
Fixes #
#1349
#1347 
**Checklist**
=> feat: update front-end README

automation/tests/loginTests.test.js, automation/tests/registrationTests.test.js, front-end/src/main/services/localUser/organizationCredentials.ts, front-end/src/renderer/components/DataMigration/DecryptMnemonicPhrase.vue, front-end/src/renderer/components/ForgotPasswordModal.vue, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/DecryptKeyModal.vue, front-end/src/renderer/components/UserPasswordModal.vue, front-end/src/renderer/components/ui/AppPasswordInput.vue, front-end/src/renderer/pages/AccountSetup/components/NewPassword.vue, front-end/src/renderer/pages/Migrate/components/DecryptRecoveryPhraseForm.vue, front-end/src/renderer/pages/Migrate/components/SetupOrganizationForm.vue, front-end/src/renderer/pages/Migrate/components/SetupPersonalForm.vue, front-end/src/renderer/pages/OrganizationLogin/OrganizationLogin.vue, front-end/src/renderer/pages/Settings/components/ProfileTab.vue, front-end/src/renderer/pages/UserLogin/UserLogin.vue, front-end/src/renderer/utils/validator.ts, front-end/src/tests/main/services/localUser/organizationCredentials.spec.ts
Password inputs have a reveal button added by default. In only a couple of cases, where a confirm password input is present, the reveal button is not visible.
Fixes https://github.com/hashgraph/hedera-transaction-tool/issues/1291, https://github.com/hashgraph/hedera-transaction-tool/issues/1130
=> feat: password input form and logic updates

front-end/src/main/shared/interfaces/organization/userKeys/IUserKey.ts, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/DecryptKeys.vue, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/EncryptedKeysBox.vue, front-end/src/renderer/components/KeyPair/ImportEncrypted/components/SelectEncryptedKeysModal.vue, front-end/src/renderer/pages/Migrate/Migrate.vue, front-end/src/renderer/pages/Migrate/components/BeginKeysImport.vue, front-end/src/renderer/pages/Migrate/components/SelectKeys.vue, front-end/src/renderer/services/encryptedKeys.ts, front-end/src/renderer/styles/_ui-elements.scss
- Selection interface (SelectKeys.vue - new step from the migration process) where users can pick specific keys for migration.
- Custom logic to handle initial decryption so the user can read the data.
- Updated all relevant components.
#1267
=> feat: allow user to select keys for migration

front-end/src/renderer/App.vue, front-end/src/renderer/components/ForgotPasswordModal.vue, front-end/src/renderer/components/GlobalAppProcesses/components/DetectKeychain.vue, front-end/src/renderer/components/ImportExternalPrivateKeyModal.vue, front-end/src/renderer/components/Transaction/Create/BaseTransaction/BaseTransaction.vue, front-end/src/renderer/components/Transaction/Create/FileContents/FileContents.vue, front-end/src/renderer/components/ui/AppModal.vue, front-end/src/renderer/components/ui/AppRecoveryPhraseWord.vue, front-end/src/renderer/main.ts, front-end/src/renderer/pages/AccountSetup/components/Import.vue, front-end/src/renderer/pages/AccountSetup/components/KeyPairs.vue, front-end/src/renderer/pages/Accounts/LinkExistingAccount/LinkExistingAccount.vue, front-end/src/renderer/pages/ContactList/SignUpUser/SignUpUser.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/pages/Files/LinkExistingFile/LinkExistingFile.vue, front-end/src/renderer/pages/Migrate/components/SetupOrganizationForm.vue, front-end/src/renderer/pages/Migrate/components/SetupPersonalForm.vue, front-end/src/renderer/pages/OrganizationLogin/OrganizationLogin.vue, front-end/src/renderer/pages/RestoreKey/RestoreKey.vue, front-end/src/renderer/pages/Settings/components/ProfileTab.vue, front-end/src/renderer/pages/UserLogin/UserLogin.vue, front-end/src/renderer/utils/autoFocus.ts, front-end/src/renderer/utils/index.ts
Added custom vue directive to focus first input/textarea/select of a container element.
Event listener to refocus on modal closing.
Switch between inputs in AppRecoveryPhraseWord with arrows (keyboard).
#909
=> feat: add focus on form fields

NOTICE, automation/package.json, automation/pnpm-lock.yaml, back-end/apps/chain/src/execute/execute.service.spec.ts, back-end/libs/common/src/utils/sdk/index.ts, back-end/package.json, back-end/pnpm-lock.yaml, front-end/package.json, front-end/pnpm-lock.yaml, front-end/src/main/modules/ipcHandlers/utils.ts, front-end/src/main/utils/hederaSpecialFiles.ts, front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue, front-end/src/renderer/components/Transaction/Details/AccountApproveAllowanceDetails.vue, front-end/src/renderer/components/Transaction/TransactionProcessor/components/BigFilePersonalRequestHandler.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/utils/sdk/index.ts
DAB transactions were failing due to SDK issues. Now that a testing environment has been setup, we were able to identify these issues and resolve them. 
Fixes #1269 
**Checklist**
=> feat: update @hashgraph/sdk to test DAB transactions

front-end/src/renderer/components/SaveDraftButton.vue, front-end/src/renderer/components/modals/SaveTransactionGroupModal.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/stores/storeTransactionGroup.ts
This pull request fixes the following transaction group bugs:
- incorrect navigation when discarding a transaction group
- incorrect navigation when saving a transaction group
- error when saving empty transaction group
- inability to execute multiple duplicated transactions
Fixes #
#972 
#975 
#976
=> fix: transaction group bugs

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
Update the version numbers for the backend.
Fixes #
**Checklist**
=> bump: upgrade version numbers to `0.6.0`

front-end/src/renderer/pages/Migrate/components/SetupPersonalForm.vue
This pull request updates the personal buttons in the migration flow
=> feat: reorder buttons in migration personal

front-end/src/renderer/pages/Migrate/Migrate.vue, front-end/src/renderer/pages/Migrate/components/DecryptRecoveryPhrase.vue, front-end/src/renderer/pages/Migrate/components/DecryptRecoveryPhraseForm.vue
Changed text in modal for enteric recovery phrase password
#1310
=> fix: text in Recovery phrase password form

front-end/src/renderer/components/Transaction/TransactionInfoControls.vue, front-end/src/renderer/pages/TransactionDetails/TransactionDetails.vue
Update description text for transactions 
Fixes #1403 
**Checklist**
=> Update description text for transactions 

automation/pages/SettingsPage.js, automation/tests/settingsTests.test.js, front-end/src/renderer/pages/RestoreKey/RestoreKey.vue
Removed the first step from Import (recovery phrase).
#1391 
**Fixes**:
I saw there is a check to skip steps if (user.recoveryPhrase). Moved it in onBeforeMount
=> fix: remove step from Import

front-end/src/renderer/components/ComplexKey/ComplexKeyAddPublicKeyModal.vue
Button style fix in ComplexKeyAddPublicKeyModal
#1334
=> fix: button style in ComplexKey

NOTICE, automation/package.json, automation/pnpm-lock.yaml
**Description**: This PR updates the playwright dependency used in the automation project.
Fixes #
**Checklist**
=> chore: Update playwright dependency

front-end/README.md
Fixed README, had incorrect directory in instructions
=> Fix front end readme

.gitignore, automation/README.md, automation/pages/GroupPage.js, automation/pages/TransactionPage.js, automation/tests/groupTransactionTests.test.js, automation/tests/organizationContactListTests.test.js, automation/tests/organizationGroupTests.test.js, automation/utils/csvGenerator.js, front-end/electron-builder.yml, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/pages/TransactionGroupDetails/TransactionGroupDetails.vue, front-end/src/renderer/pages/Transactions/components/Drafts.vue, front-end/src/renderer/pages/Transactions/components/History.vue, front-end/src/renderer/pages/Transactions/components/InProgress.vue, front-end/src/renderer/pages/Transactions/components/ReadyForExecution.vue, front-end/src/renderer/pages/Transactions/components/ReadyForReview.vue, front-end/src/renderer/pages/Transactions/components/ReadyToSign.vue
**Description**: This PR includes automation tests for organization transaction group
Fixes #1218
**Checklist**
=> test: Add tests for organization transaction group

front-end/src/renderer/pages/Settings/components/GeneralTab/components/NetworkSettings.vue
This pull request fixes the highlighting of the custom network
Fixes #
#1335
=> fix: custom network highlighting

front-end/src/renderer/components/EmptyTransactions.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/pages/TransactionGroupDetails/TransactionGroupDetails.vue, front-end/src/renderer/pages/Transactions/components/Drafts.vue, front-end/src/renderer/pages/Transactions/components/History.vue, front-end/src/renderer/pages/Transactions/components/InProgress.vue, front-end/src/renderer/pages/Transactions/components/ReadyForExecution.vue, front-end/src/renderer/pages/Transactions/components/ReadyForReview.vue, front-end/src/renderer/pages/Transactions/components/ReadyToSign.vue
This pull request fixes the transaction group details rendering
Fixes #
#1429
=> fix: page not scrollable for large groups

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
=> version: updating backend/frontend versions to 0.7.0

NOTICE, front-end/package.json, front-end/pnpm-lock.yaml
This pull request updates the electron version
=> feat: update electron

automation/pages/OrganizationPage.js, automation/tests/organizationSettingsTests.test.js, front-end/src/renderer/components/Organization/AddOrganizationModal.vue, front-end/src/renderer/components/Organization/OrganizationStatusModal.vue, front-end/src/renderer/pages/Settings/components/OrganizationsTab.vue
This pull request includes information about the organization in the not reachable modal
Fixes #
#1413
=> feat: include name in organization not reachable

automation/pages/GroupPage.js, automation/tests/groupTransactionTests.test.js, automation/tests/organizationGroupTests.test.js, front-end/src/renderer/components/EmptyTransactions.vue, front-end/src/renderer/components/GroupActionModal.vue, front-end/src/renderer/components/Transaction/TransactionGroupProcessor.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/stores/storeTransactionGroup.ts
This pull request fixes the execution of the personal group transactions
=> fix: personal group transactions

back-end/libs/common/src/constants/notificationTypeEmailSubjects.ts
Update the subject line for email notifications
Fixes #1482 
**Checklist**
=> feat: update email subject line text

front-end/src/renderer/components/ui/AppPublicKeyInput.vue
This pull request fixes an issue where the dynamic padding was not properly calculated
Fixes #
#1485
=> fix: public key dynamic padding

front-end/src/renderer/components/Transaction/TransactionGroupProcessor.vue
This pull request fixes the bug when executing a transaction group draft with more than two transactions
Fixes # #1443
=> fix: tranasaction group draft execution bug

back-end/apps/notifications/src/receiver/services/reminder-handler.service.ts
This pull request fixes a typo in an email  about approaching the valid start
=> fix: email typo

front-end/src/renderer/pages/MigrateRecoveryPhraseHash/MigrateRecoveryPhraseHash.vue
The wording has been adjusted to indicate that the app will be missing features, but somewhat usable even if the mnemonic is not reentered. 
Any other concerns related to this issue will likely need to be handled outside of the code, as the issue is not relevant in the future. 
Fixes #1436
=> chore: updated wording of Mnemonic matching message

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
=> bump: version 0.8.0

NOTICE, automation/package.json, automation/pnpm-lock.yaml
=> chore: Update playwright version

front-end/src/main/services/localUser/complexKeys.ts, front-end/src/preload/localUser/complexKeys.ts, front-end/src/renderer/components/ComplexKey/ComplexKey.vue, front-end/src/renderer/components/ComplexKey/ComplexKeyModal.vue, front-end/src/renderer/components/ComplexKey/ComplexKeyThreshold.vue, front-end/src/renderer/components/KeyField.vue, front-end/src/renderer/components/KeyStructure.vue, front-end/src/renderer/services/complexKeysService.ts
Allow threshold nicknames
Fixes #1342 
**Checklist**
=> feat: allow threshold nicknames

automation/pages/RegistrationPage.js
=> test: Fix failing transaction test

front-end/src/renderer/components/modals/ResetDataModal.vue
The updated text explains what will happen if the app is reset.
Fixes #1466
=> chore: update reset app message text for user

back-end/apps/api/src/auth/auth.controller.spec.ts, back-end/apps/api/src/auth/auth.controller.ts, back-end/apps/api/src/auth/auth.service.spec.ts, back-end/apps/api/src/auth/auth.service.ts, back-end/apps/api/src/auth/dtos/elevate-admin.dto.ts, back-end/apps/api/src/auth/dtos/index.ts, back-end/apps/api/test/spec/auth.e2e-spec.ts, front-end/src/renderer/components/Contacts/ContactDetails.vue, front-end/src/renderer/components/Contacts/ElevateContactModal.vue, front-end/src/renderer/pages/ContactList/ContactList.vue, front-end/src/renderer/services/organization/auth.ts
This pull request adds functionality for elevating regular users to admins
Fixes #1148
=> feat: allow users to elevate other admins

NOTICE, front-end/package.json, front-end/pnpm-lock.yaml
This pull request updates vitest
=> chore: update Vitest

back-end/apps/api/src/user-keys/user-keys-all.controller.spec.ts, back-end/apps/api/src/user-keys/user-keys-all.controller.ts, back-end/apps/api/src/user-keys/user-keys.module.ts, back-end/apps/api/src/user-keys/user-keys.service.spec.ts, back-end/apps/api/src/user-keys/user-keys.service.ts, front-end/src/renderer/components/Contacts/ContactDetails.vue, front-end/src/renderer/pages/ContactList/ContactList.vue, front-end/src/renderer/services/organization/userKeys.ts, front-end/src/renderer/stores/storeContacts.ts
This pull request updates the fetching of the user keys. It is now paginated and prefetched whenever a user is selected in the contact list
Fixes #1149
=> fix: user keys fetching

front-end/src/renderer/components/UserModeSelect.vue
Add a title type item to the dropdown ('Organizations')
#1244
=> feat: organizations dropdown title

front-end/src/main/shared/constants/index.ts, front-end/src/renderer/composables/user/useAfterOrganizationSelection.ts, front-end/src/renderer/pages/AccountSetup/AccountSetup.vue, front-end/src/renderer/pages/AccountSetup/components/Generate.vue, front-end/src/renderer/pages/AccountSetup/components/GenerateOrImport.vue, front-end/src/renderer/router/guards.ts, front-end/src/renderer/stores/storeUser.ts, front-end/src/renderer/utils/index.ts, front-end/src/renderer/utils/localServices.ts
This pull request adds a skip button in the account setup page so that organizational users can skip the account setup
Fixes #1307
=> feat: allow skipping account setup

NOTICE, automation/package.json, back-end/apps/api/package.json, back-end/apps/api/src/transactions/transactions.service.spec.ts, back-end/apps/api/src/transactions/transactions.service.ts, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json, front-end/src/renderer/pages/TransactionDetails/components/TransactionDetailsHeader.vue
Manual submission allowed the user to submit the transaction before the transaction's validStart. The network would return an error indicating that the transaction's validStart is invalid. Now, submitting the transaction manually will execute if the validStart is now valid, or will schedule the transaction to be executed at the appropriate time.
Fixes #1540 
**Checklist**
=> Submit manually execution

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
=> bump: v0.9.0 version bump

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
=> bump: app version 0.10.0

front-end/src/renderer/components/AccountIdInput.vue, front-end/src/renderer/components/Transaction/Create/FileAppend/FileAppendFormData.vue, front-end/src/renderer/components/Transaction/Create/FileContents/FileContents.vue, front-end/src/renderer/components/Transaction/Create/FileUpdate/FileUpdateFormData.vue, front-end/src/renderer/components/Transaction/Create/Freeze/FreezeFormData.vue, front-end/src/renderer/components/Transaction/Create/SystemData/SystemDataFormData.vue, front-end/src/renderer/pages/Accounts/LinkExistingAccount/LinkExistingAccount.vue, front-end/src/renderer/pages/Files/LinkExistingFile/LinkExistingFile.vue
Support arbitrary realms and shards
Fixes #1545 
**Checklist**
=> fix: remove '0.0.' prefill

front-end/src/main/services/localUser/complexKeys.ts, front-end/src/preload/localUser/complexKeys.ts, front-end/src/renderer/components/ComplexKey/ComplexKey.vue, front-end/src/renderer/components/ComplexKey/ComplexKeyModal.vue, front-end/src/renderer/components/ComplexKey/ComplexKeyThreshold.vue, front-end/src/renderer/components/KeyField.vue, front-end/src/renderer/components/KeyStructure.vue, front-end/src/renderer/services/complexKeysService.ts
This feature will require a redesign of the ComplexKey structure and how it is saved and used throughout the app.
Further information related the problems of building on the ComplexKey as it is currently designed can be found here: https://github.com/hashgraph/hedera-transaction-tool/pull/1544 and in the related issues.
Local testing passed, as well as manual testing 
**Checklist**
=> revert: removing threshold nicknaming feature

front-end/src/renderer/components/ui/AppAutoComplete.vue, front-end/src/renderer/utils/index.ts
With removing of the auto fill of the realm/shard, the autocomplete feature no longer fully worked. If the user started typing only the account number of the accountId, the auto complete feature could not find a good match and make suggestions. Now, a prefix suggestion is made in addition to the postfix.
=> fix: prefix suggestions and smart autocomplete

back-end/libs/common/src/constants/index.ts, back-end/libs/common/src/models/node-delete-transaction.model.ts, back-end/libs/common/src/utils/sdk/transaction.ts, back-end/libs/common/src/utils/transaction/index.ts, front-end/src/renderer/utils/sdk/getData.ts, front-end/src/renderer/utils/transactionSignatureModels/index.ts, front-end/src/renderer/utils/transactionSignatureModels/node-delete-transaction.model.ts
This pull request adjusts the requirements for the DAB transactions to the latest signing requirements
=> feat: verify node keys in DAB transactions

front-end/src/renderer/pages/Accounts/Accounts.vue, front-end/src/renderer/pages/ContactList/SignUpUser/SignUpUser.vue, front-end/src/renderer/pages/Files/Files.vue
Allow the user to add multiple users in one step
Fixes #1032
**Checklist**
=> 1032 allow admin user to add multiple users to back end in one step

NOTICE, back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
=> bump: v0.11.0

NOTICE, automation/package.json, automation/pnpm-lock.yaml, back-end/package.json, back-end/pnpm-lock.yaml, front-end/package.json, front-end/pnpm-lock.yaml, front-end/src/renderer/pages/Accounts/Accounts.vue, front-end/src/renderer/pages/ContactList/SignUpUser/SignUpUser.vue, front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue, front-end/src/renderer/pages/RestoreMissingKeys/RestoreMissingKeys.vue, front-end/src/renderer/services/keyPairService.ts, front-end/src/renderer/utils/index.ts, front-end/src/renderer/utils/transferTransactions.ts
This pull request updates vulnerable packages.
!Important note: The @hashgraph/sdk has a newer version, in which the SDK is minified. This introduces specific breaking changes. The current PR does not update the SDK to the minified version as updates from the SDK team should happen that will smoothen the update process here
Fixes #1613
=> Fix vulnerable dependencies

back-end/apps/api/package.json, back-end/apps/chain/package.json, back-end/apps/notifications/package.json, back-end/package.json, front-end/package.json
=> bump: v0.13.0

front-end/src/renderer/components/Transaction/Create/NodeCreate/NodeFormData.vue
Enable gRPC web proxy fields.
Fixes #1718 
**Checklist**
=> feat: enable gRPC web proxy fields

front-end/README.md
This PR updates the README to clarify setup requirements and provide additional troubleshooting guidance.
- Add explicit prerequisites with version checks (Node.js, pnpm, python-setuptools)
- Reformat prerequisites into a bullet/sub-bullet list for readability
- Expand the troubleshooting section to include Prisma client fixes and ENOENT Electron distribution resolution
**Related issue(s)**: 
Fixes #1757 
No functional code changes — documentation only. Verified formatting locally.
**Checklist**
=> (docs): Improve README with prerequisites, troubleshooting, and setup instructions

back-end/apps/api/src/transactions/transactions.controller.spec.ts, back-end/apps/api/src/transactions/transactions.service.ts, back-end/libs/common/src/pipes/transaction-id.pipe.spec.ts, back-end/libs/common/src/pipes/transaction-id.pipe.ts, back-end/libs/common/src/utils/transaction/index.ts, back-end/package.json, front-end/src/renderer/components/TransactionImportModal.vue, front-end/src/renderer/pages/TransactionDetails/TransactionDetails.vue, front-end/src/renderer/utils/index.ts, front-end/src/renderer/utils/signatureTools.ts
These are the changes I did to make the full flow work. There is still more to be done, and there might be a few issues (my k8s cluster died before I could run all tests). Take a look, let me know when you think
=> fix: all adjustments made thus far to get it working.
